## Deliverable 1: Linear Regression to Predict MPG

# Importing Dependencies
library(dplyr)

# Deliverable 1:
# Import and read the data files.
MechaCar_mpg <- read.csv(file='MechaCar_mpg.csv', check.names= F, stringsAsFactors = F)

# Checking the dataframe.
head(MechaCar_mpg)

#5. Perform linear regression using the lm() function
lm(mpg ~ vehicle_length + spoiler_angle + ground_clearance + AWD, data = MechaCar_mpg)

#6. Using the summary() function, determine the p-value and the r-squared value for the linear regression model.
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=MechaCar_mpg))

# Deliverable 2:
# import and read in the Suspension_Coil.csv file as a table.
Susp_Coil <- read.csv(file='Suspension_Coil.csv', check.names= F, stringsAsFactors = F)

#3. Creates a total_summary dataframe using the summarize() function to get the mean, median, variance, and standard deviation.
total_summary <- Susp_Coil %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI))

#3.1 Checking the dataframe.
head(total_summary)

#4. using the group_by() and the summarize() functions to group each manufacturing lot by the mean, median, variance, and standard deviation
lot_summary <- Susp_Coil %>% group_by(Manufacturing_Lot) %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI))

#4.1 Checking the dataframe.
head(lot_summary)

# Deliverable 3:
# PSI across all manufacturing lots is statistically different from the population mean of 1,500 pounds per square inch.
t.test(Susp_Coil$PSI,mu=1500)

# Determine if the PSI for each manufacturing lot is statistically different from the population mean of 1,500 pounds per square inch.
t.test(subset(Susp_Coil$PSI,Susp_Coil$Manufacturing_Lot == "Lot1"),mu=1500)
t.test(subset(Susp_Coil$PSI,Susp_Coil$Manufacturing_Lot == "Lot2"),mu=1500)
t.test(subset(Susp_Coil$PSI,Susp_Coil$Manufacturing_Lot == "Lot3"),mu=1500)